# 필요한 라이브러리

In [5]:
# 데이터 프레임
import pandas as pd

In [7]:
# 그래프
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
# 전처리 파일 찾을 수 있게 폴더 위치 지정
import sys
import os

# 현재 실행 중인 디렉토리 확인
print("현재 디렉토리:", os.getcwd())

# package 폴더가 있는 경로 추가
sys.path.append(os.path.abspath("../../package"))

# 이제 import 가능!
from preprocessing.test_pipeline import preprocessing_customer_data

현재 디렉토리: C:\Users\user\Documents\hk-toss-middle-project\notebooks\EDA

# 파일 불러오기

In [21]:
df_22 = pd.read_csv("E:/토스 중간 프로젝트/11.통신카드CB 결합정보/202212_통신카드CB결합.csv")

In [23]:
df_21 = pd.read_csv("E:/토스 중간 프로젝트/11.통신카드CB 결합정보/202112_통신카드CB결합.csv")

In [25]:
df = preprocessing_customer_data(df_21, df_22)

In [27]:
df_22

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202212,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,202212,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,202212,SYN_2,1,30,420,11,11.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,202212,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202212,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329995,202212,SYN_329995,1,55,510,11,11.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
329996,202212,SYN_329996,2,60,910,41,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329997,202212,SYN_329997,2,20,910,30,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329998,202212,SYN_329998,2,45,420,29,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329999,202212,SYN_329999,1,55,420,41,41.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
df_21

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202112,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,0,0,0
1,202112,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,202112,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,202112,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202112,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329995,202112,SYN_329995,1,55,510,11,11.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
329996,202112,SYN_329996,2,60,910,41,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329997,202112,SYN_329997,2,20,910,30,NaN,0,0,0,...,0,1,0,1,0,0,0,-1,0,0
329998,202112,SYN_329998,2,45,420,29,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329999,202112,SYN_329999,1,55,420,41,41.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS,exited
0,202212,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,202212,SYN_1,2,50,910,41,11.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,202212,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202212,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,202212,SYN_5,2,55,510,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329994,202212,SYN_329994,1,40,510,41,NaN,1,0,0,...,0,0,0,0,0,0,0,0,0,0
329995,202212,SYN_329995,1,55,510,11,11.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
329996,202212,SYN_329996,2,60,910,41,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329998,202212,SYN_329998,2,45,420,29,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329999,202212,SYN_329999,1,55,420,41,41.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0